# Generated by Django 4.1.5 on 2023-01-25 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_num',
            field=models.CharField( max_length=12, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_num',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
