# Generated by Django 4.1.5 on 2023-01-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_customuser_phone_num_student_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_num',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
