# Generated by Django 4.1.5 on 2023-01-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_student_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone_num',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
