# Generated by Django 4.1.5 on 2023-01-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_staff_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_num',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_num',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
