# Generated by Django 4.1.5 on 2023-01-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_student_aadhar_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_num',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
