# Generated by Django 4.1.5 on 2023-01-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_staff_department_subject_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aadhar_num',
            field=models.IntegerField(max_length=16, null=True),
        ),
    ]
