# Generated by Django 4.1.5 on 2023-02-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_course_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='course',
        ),
    ]
