# Generated by Django 4.1.5 on 2023-02-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_staff_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_num',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='register_num',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='relegion',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
