# Generated by Django 4.1.5 on 2023-02-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_student_admission_num_student_register_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='aadhar_num',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_num',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
