# Generated by Django 4.1.5 on 2023-02-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_staff_aadhar_num_staff_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qualification',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
