# Generated by Django 4.1.5 on 2023-02-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_customuser_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='relegion',
            new_name='religion',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='qualification',
        ),
    ]
