# Generated by Django 4.1.5 on 2023-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_rename_relegion_student_religion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='file',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
