# Generated by Django 4.1.5 on 2023-02-19 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_remove_customuser_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mark_list',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mark_list',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
