# Generated by Django 4.1.5 on 2023-02-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_customuser_mark_list_student_mark_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mark_list',
        ),
    ]
