# Generated by Django 4.1.5 on 2023-02-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_remove_customuser_mark_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mark_list',
        ),
    ]
