# Generated by Django 4.1.5 on 2023-02-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_remove_student_mark_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.session'),
        ),
    ]
